In [2]:
#1a)
import numpy as np
ar=np.random.randint(0,21,size=15)
print(ar)
a=ar.reshape(3,5)
print(a)
print(a.shape)
max_values=a.argmax(axis=1)
for i,j in enumerate(max_values):
  a[i,j]=0
print(a)

ar1=np.zeros((4,3),dtype=np.int32)
print(ar1.shape)
print(type(ar1))
print(ar1.dtype)

[ 0 12  3 10 10 13  8 17 20 15 20 14 20  0 13]
[[ 0 12  3 10 10]
 [13  8 17 20 15]
 [20 14 20  0 13]]
(3, 5)
[[ 0  0  3 10 10]
 [13  8 17  0 15]
 [ 0 14 20  0 13]]
(4, 3)
<class 'numpy.ndarray'>
int32


In [5]:
#1b)
ar2=np.array([[3,-2],[1,0]])
eigvals,eigvecs=np.linalg.eig(ar2)
print("EigenValues:",eigvals)
print("Eigen Vectors:",eigvecs)

EigenValues: [2. 1.]
Eigen Vectors: [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [6]:
#1c)
ar3=np.array([[0,1,2],[3,4,5]])
sum_diag=np.trace(ar3)
print(sum_diag)

4


In [7]:
#1d)
ar4=np.array([[1,2],[3,4],[5,6]])
ar4_reshape1=ar4.reshape(2,3)
ar4_reshape2=ar4.reshape(3,2)
print(ar4_reshape1)
print(ar4_reshape2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
